---
- name: Reload shell profile
  ansible.builtin.shell: source {{ ansible_env.HOME }}/.profile
  args:
    executable: /bin/bash
  changed_when: false

- name: Update uv
  ansible.builtin.command: uv self update
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  changed_when: false
