---
- name: Install dnf packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dnf_packages | default([]) }}"
  become: true
  when: dnf_packages is defined

- name: Add RPM Fusion repositories
  ansible.builtin.dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true
  when: enable_rpmfusion | default(false)
