---
- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: '0755'

- name: Download and install Nerd Fonts
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.zip"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: true
    creates: "{{ ansible_env.HOME }}/.local/share/fonts/{{ item }}"
  loop: "{{ nerd_fonts | default(['JetBrainsMono', 'FiraCode', 'Hack']) }}"
  register: font_download
  failed_when: false

- name: Update font cache
  ansible.builtin.command: fc-cache -fv
  notify: "update font cache"
  changed_when: true

- name: Install fontconfig on Debian/Ubuntu
  ansible.builtin.package:
    name: fontconfig
    state: present
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install fontconfig on Fedora
  ansible.builtin.package:
    name: fontconfig
    state: present
  become: true
  when: ansible_distribution == "Fedora"
