---
- name: Configure macOS system preferences
  ansible.builtin.shell: |
    # Configure macOS system settings
    defaults write com.apple.dock autohide -bool true
    defaults write com.apple.dock tilesize -int 36
    defaults write com.apple.finder ShowPathbar -bool true
    defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
    defaults write com.apple.screencapture location -string "{{ ansible_env.HOME }}/Pictures/Screenshots"
    killall Dock
    killall Finder
  args:
    executable: /bin/bash
  environment:
    BASH_ENV: /dev/null
  changed_when: false
  when: configure_macos_defaults | default(true)
