---
- name: Install xdg-user-dirs (Arch)
  pacman:
    name: xdg-user-dirs
    state: present
  become: true
  when: ansible_distribution == "Archlinux"

- name: Install xdg-user-dirs (Debian/Ubuntu)
  ansible.builtin.apt:
    name: xdg-user-dirs
    state: present
  become: true
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install xdg-user-dirs (Fedora)
  ansible.builtin.dnf:
    name: xdg-user-dirs
    state: present
  become: true
  when: ansible_distribution == "Fedora"

- name: Create user-dirs.dirs configuration
  ansible.builtin.template:
    src: user-dirs.dirs.j2
    dest: "{{ xdg_config_home }}/user-dirs.dirs"
    mode: '0644'

- name: Create user-dirs.locale configuration
  ansible.builtin.copy:
    content: |
      en_GB
    dest: "{{ xdg_config_home }}/user-dirs.locale"
    mode: '0644'

- name: Run xdg-user-dirs-update
  ansible.builtin.command: xdg-user-dirs-update
  changed_when: false
