---
- name: Install Homebrew formulas
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_formulas }}"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"
