---
- name: Add Homebrew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"
  environment:
    PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}"
