---
dependencies:
  - role: mise

galaxy_info:
  author: your_name
  description: Editor configuration (Neovim/Vim)
  company: personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - neovim
    - vim
    - editor
    - development
